# Validates Functions Framework with GCF buildpacks.
name: Buildpack Integration Test
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  # Runs every day on 12:00 AM PST
  schedule:
    - cron: "0 0 * * *"

# Declare default permissions as read only.
permissions: read-all

jobs:
  java11-buildpack-test:
    uses: GoogleCloudPlatform/functions-framework-conformance/.github/workflows/buildpack-integration-test.yml@main
    with:
      http-builder-source: '/tmp/tests/conformance'
      http-builder-target: 'com.google.cloud.functions.conformance.HttpConformanceFunction'
      cloudevent-builder-source: '/tmp/tests/conformance'
      cloudevent-builder-target: 'com.google.cloud.functions.conformance.CloudEventsConformanceFunction'
      prerun: 'invoker/conformance/prerun.sh'
      builder-runtime: 'java11'
      builder-runtime-version: '11'
      builder-url: gcr.io/gae-runtimes/buildpacks/google-gae-22/java/builder:latest
  java17-buildpack-test:
    uses: GoogleCloudPlatform/functions-framework-conformance/.github/workflows/buildpack-integration-test.yml@main
    with:
      http-builder-source: '/tmp/tests/conformance'
      http-builder-target: 'com.google.cloud.functions.conformance.HttpConformanceFunction'
      cloudevent-builder-source: '/tmp/tests/conformance'
      cloudevent-builder-target: 'com.google.cloud.functions.conformance.CloudEventsConformanceFunction'
      prerun: 'invoker/conformance/prerun.sh'
      builder-runtime: 'java17'
      builder-runtime-version: '17'
      builder-url: gcr.io/gae-runtimes/buildpacks/google-gae-22/java/builder:latest