name: Java Lint CI
on:
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
      with:
        disable-sudo: true
        egress-policy: block
        allowed-endpoints: >
          github.com:443
          repo.maven.apache.org:443
    - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
    - name: Set up JDK
      uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
      with:
        java-version: 17.x
        distribution: temurin
    - name: Build API with Maven
      run: (cd functions-framework-api/ && mvn install)
    - name: Lint Functions Framework API
      run: (cd functions-framework-api/ && mvn clean verify -DskipTests -P lint)
    - name: Build Invoker with Maven
      run: (cd functions-framework-api/ && mvn install)
    - name: Lint Invoker
      run: (cd invoker/ && mvn clean verify -DskipTests -P lint)
  formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0 # v2 minimum required
      - name: Set up JDK
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          java-version: 21.x
          distribution: temurin
      - name: Run formatter
        id: formatter
        uses: axel-op/googlejavaformat-action@dbff853fb823671ec5781365233bf86543b13215 # v3
        with:
          args: "--replace"
          skip-commit: true
      - name: Print diffs
        run: git --no-pager diff --exit-code
